import{S as p,i as c}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();function m(s){const t="https://pixabay.com/api/",a="45109890-d15cee52eedc615dd4ac8bedf",o=new URLSearchParams({key:a,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${t}?${o}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).catch(console.log)}const i=document.querySelector(".card-container"),l=document.querySelector(".js-loader");i.addEventListener("click",s=>s.preventDefault());function h(){l.style.display="inline-block"}function g(){l.style.display="none"}function y(s){let t="";s.map(({webformatURL:o,largeImageURL:e,tags:r,likes:n,views:d,comments:f,downloads:u})=>{t+=`<li class="list-group-item"><div class="search-card">
   <div class="card-img-box">
     <a clas="card-link" href="${e}"><img class="card-img" src="${o}" alt="${r}"></a>
   </div>
   <div class="card-box-text">
     <p class="card-text">Likes<br><span>${n}</span></p>
     <p class="card-text">Views<br><span>${d}</span></p>
     <p class="card-text">Comments<br><span>${f}</span></p>
     <p class="card-text">Downloads<br><span>${u}</span></p>
   </div>
</div></li>`}).join(""),i.innerHTML=t,new p(".card-container a",{captionsData:"alt",captionDelay:250,overlayOpacity:.9}).refresh()}const b=document.querySelector(".js-form-container");b.addEventListener("submit",v);function v(s){s.preventDefault(),h();const t=s.currentTarget,a=t.elements.search.value.toLowerCase().trim();if(!a){c.error({iconUrl:"./img/Vector.svg",message:"Please enter the data in the input field",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"});return}m(a).then(o=>(o.hits.length||c.error({iconUrl:"./img/Vector.svg",message:"Sorry, there are no images matching<br>your search query. Please try again!",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"}),o)).then(o=>{y(o.hits)}).catch(console.log).finally(()=>{g(),t.reset()})}
//# sourceMappingURL=commonHelpers.js.map
